// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.CMS.Application.DependencyInjection.AddMediatRBehaviors(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.CMS.Application.DependencyInjection.AddApplicationServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:Myrtus.CMS.Application.Features.Users.Queries.GetUser.GetUserQueryResponse.Roles")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:Myrtus.CMS.Application.Features.Users.Queries.GetLoggedInUser.UserResponse.Roles")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:Myrtus.CMS.Application.Features.Users.Queries.GetAllUsersByRoleId.GetAllUsersByRoleIdQueryResponse.Roles")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:Myrtus.CMS.Application.Features.Users.Queries.GetAllUsers.GetAllUsersQueryResponse.Roles")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.CMS.Application.Features.Users.Commands.Update.UpdateUserRoles.UpdateUserRolesCommandHandler.Handle(Myrtus.CMS.Application.Features.Users.Commands.Update.UpdateUserRoles.UpdateUserRolesCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Ardalis.Result.Result{Myrtus.CMS.Application.Features.Users.Commands.Update.UpdateUserRoles.UpdateUserRolesCommandResponse}}")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.CMS.Application.Features.Roles.Queries.GetRoleById.GetRoleByIdQueryValidator.#ctor")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:Myrtus.CMS.Application.Features.Roles.Queries.GetRoleById.GetRoleByIdQueryResponse.Permissions")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.CMS.Application.Features.Roles.Commands.Update.UpdateRoleName.UpdateRoleNameCommandHandler.Handle(Myrtus.CMS.Application.Features.Roles.Commands.Update.UpdateRoleName.UpdateRoleNameCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Ardalis.Result.Result{Myrtus.CMS.Application.Features.Roles.Commands.Update.UpdateRoleName.UpdateRoleNameCommandResponse}}")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.CMS.Application.Features.Roles.Commands.Update.UpdatePermissions.UpdateRolePermissionsCommandHandler.Handle(Myrtus.CMS.Application.Features.Roles.Commands.Update.UpdatePermissions.UpdateRolePermissionsCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Ardalis.Result.Result{Myrtus.CMS.Application.Features.Roles.Commands.Update.UpdatePermissions.UpdateRolePermissionsCommandResponse}}")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.CMS.Application.Features.Roles.Commands.Delete.DeleteRoleCommandHandler.Handle(Myrtus.CMS.Application.Features.Roles.Commands.Delete.DeleteRoleCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Ardalis.Result.Result{Myrtus.CMS.Application.Features.Roles.Commands.Delete.DeleteRoleCommandResponse}}")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.CMS.Application.Features.Roles.Commands.Create.CreateRoleCommandHander.Handle(Myrtus.CMS.Application.Features.Roles.Commands.Create.CreateRoleCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Ardalis.Result.Result{Myrtus.CMS.Application.Features.Roles.Commands.Create.CreateRoleCommandResponse}}")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.CMS.Application.Features.Accounts.RegisterUser.RegisterUserCommandValidator.#ctor")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.CMS.Application.Features.Accounts.RegisterUser.RegisterUserCommandHandler.Handle(Myrtus.CMS.Application.Features.Accounts.RegisterUser.RegisterUserCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Ardalis.Result.Result{System.Guid}}")]
