version: '3.4'

services:
  myrtuscms-api:
    image: ${DOCKER_REGISTRY-}myrtuscmsapi
    container_name: MyrtusCMS.WebAPI
    build:
      context: .
      dockerfile: src/Myrtus.Clarity.WebAPI/Dockerfile
    depends_on:
      - myrtuscms-db

  myrtuscms-db:
    image: postgres:latest
    container_name: MyrtusCMS.Db
    environment:
      - POSTGRES_DB=myrtusCMS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  myrtuscms-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: MyrtusCMS.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.containers/keycloak/data:/opt/keycloak/data/import
    ports:
      - 18080:8080

  myrtuscms-seq:
    image: datalust/seq:latest
    container_name: MyrtusCMS.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    volumes:
      - ./.containers/logging/seq/data:/data

  myrtuscms-redis:
    image: redis:latest
    container_name: MyrtusCMS.Redis
    restart: always
    ports:
      - 6379:6379

  myrtuscms-redis-insight:
    image: redis/redisinsight:latest
    container_name: MyrtusCMS.RedisInsight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    environment:
      - RIHOST=redis://myrtuscms-redis:6379

  myrtuscms-mongodb:
    image: mongo:latest
    container_name: MyrtusCMS.MongoDb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./.containers/mongodb:/data/db
    ports:
      - 27017:27017
       
volumes:
  redis-insight:
