services:
  Myrtus-api:
    image: ${DOCKER_REGISTRY-}myrtusapi
    container_name: Myrtus.WebAPI
    build:
      context: .
      dockerfile: src/Myrtus.Clarity.WebAPI/Dockerfile
    depends_on:
      - Myrtus-db

  Myrtus-db:
    image: postgres:latest
    container_name: Myrtus.Db
    environment:
      - POSTGRES_DB=Myrtus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  Myrtus-seq:
    image: datalust/seq:latest
    container_name: Myrtus.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    volumes:
      - ./.containers/logging/seq/data:/data

  Myrtus-redis:
    image: redis:latest
    container_name: Myrtus.Redis
    restart: always
    ports:
      - 6379:6379

  Myrtus-redis-insight:
    image: redis/redisinsight:latest
    container_name: Myrtus.RedisInsight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    environment:
      - RIHOST=redis://Myrtus-redis:6379

  Myrtus-mongodb:
    image: mongo:latest
    container_name: Myrtus.MongoDb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./.containers/mongodb:/data/db
    ports:
      - 27017:27017
       
volumes:
  redis-insight:
