// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.DependencyInjection.AddInfrastructure(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)~Microsoft.Extensions.DependencyInjection.IServiceCollection")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.DependencyInjection.AddPersistence(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.DependencyInjection.AddAuthentication(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.DependencyInjection.AddAuthorization(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.DependencyInjection.AddCaching(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.DependencyInjection.AddHealthChecks(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.DependencyInjection.AddApiVersioning(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.DependencyInjection.AddBackgroundJobs(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.DependencyInjection.AddAuditing(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.DependencyInjection.AddSignalR(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.ApplicationDbContext.OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.SeedData.SeedUsers.SeedUsersDataAsync(Microsoft.AspNetCore.Builder.IApplicationBuilder)~System.Threading.Tasks.Task{System.Guid}")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.SeedData.SeedRoleUser.SeedRoleUserDataAsync(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.Guid)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.SeedData.SeedRoles.SeedRolesDataAsync(Microsoft.AspNetCore.Builder.IApplicationBuilder)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.SeedData.SeedRolePermissions.SeedRolePermissionsDataAsync(Microsoft.AspNetCore.Builder.IApplicationBuilder)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1849:Call async methods when in an async method", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.SeedData.SeedPermissions.SeedPermissionsDataAsync(Microsoft.AspNetCore.Builder.IApplicationBuilder)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.SeedData.SeedPermissions.SeedPermissionsDataAsync(Microsoft.AspNetCore.Builder.IApplicationBuilder)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Repositories.UserRepository.AddAsync(Myrtus.Clarity.Domain.Users.User)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Repositories.RoleRepository.AddAsync(Myrtus.Clarity.Domain.Roles.Role)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Repositories.RoleRepository.Update(Myrtus.Clarity.Domain.Roles.Role)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Repositories.Repository`1.AddAsync(`0)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Repositories.Repository`1.Update(`0)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Repositories.Repository`1.Delete(`0,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Repositories.NoSQL.NoSqlRepository`1.UpdateAsync(`0,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Repositories.NoSQL.NoSqlRepository`1.DeleteAsync(System.Linq.Expressions.Expression{System.Func{`0,System.Boolean}},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Repositories.NoSQL.AuditLogRepository.#ctor(MongoDB.Driver.IMongoDatabase)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Configurations.OutboxMessageConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Myrtus.Clarity.Core.Infrastructure.Outbox.OutboxMessage})")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Configurations.PermissionConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Myrtus.Clarity.Domain.Roles.Permission})")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Configurations.RoleConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Myrtus.Clarity.Domain.Roles.Role})")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Configurations.UserConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Myrtus.Clarity.Domain.Users.User})")]
[assembly: SuppressMessage("Style", "IDE0022:Use block body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.Authentication.Models.UserRepresentationModel.FromUser(Myrtus.Clarity.Domain.Users.User)~Myrtus.Clarity.Infrastructure.Authentication.Models.UserRepresentationModel")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Myrtus.Clarity.Infrastructure.DependencyInjection.AddMailing(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Configuration.IConfiguration)")]
